### ISSUE TITLE
ufs ls ERROR: Could not enter raw REPL.

### ISSUE THREAD

**Issue by csanyipal** [ntoll/microfs#20]
Hi,

I just installed microfs with pip3 on my Debian GNU/Linux Stretch system.
After I attached a micro:bit to my system ( but not mounted it yet ), when I run 'ufs ls' I get this output in a xfce4-terminal window:
First right away I get this message:
`ufs ls`
[Errno 16] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'

but after a while I get this:
`ufs ls`
b''
Could not enter raw REPL.

How can I solve this problem?

Best, Pal

**Comment by csanyipal** [comment]
I solve this problem by running
`uflash`
command when the micro:bit is attached to my Debian GNU/Linux system.
After I dud run 'uflash' command it's output was this:
Flashing Python to: /media/pali/MICROBIT/micropython.hex
After that command
`ufs ls`
does not return any ERROR messages.
It's output is empty ( But I thought I'd download the game that came with the micro: bit. ).

So, problem SOLVED.

**Comment by ntoll** [comment]
@csanyipal glad you sorted things out yourself..!
