### ISSUE TITLE
Error when transferring data from micro::bit

### ISSUE THREAD

**Issue by alexandros769** [ntoll/microfs#22]
Hello,
I have created a simple script that creates binary files from an incrementing value.
Each of these files should have a length of 100bytes holding 50 16-bit numbers.
For some of the files, i.e. the first one that contains values 0 to 49 when I try ufs get file the file is not transferred and the corresponding ascii characters of the binary values are dumped.
For other files the file transfer completes succesfully.
My micro::bit
Interface Version: 0253
Any ideas? 
Thanks.

**Comment by ntoll** [comment]
Hmm... not sure. What OS are you using..?

**Comment by alexandros769** [comment]
Windows 19

**Comment by dpgeorge** [comment]
@alexandros769 it might help if you could provide the full script you are running, the command-line that you invoke to get the files, and what the output is of the failed command.  That way someone can try to reproduce the problem and work out how to fix it.

**Comment by alexandros769** [comment]
The simplest thing to try this is the following:
[test.log](https://github.com/ntoll/microfs/files/4388009/test.log)
Use the attached binary file and do a:
ufs put test.log
rename the file locally and then do a:
ufs get test.log

This is what I get and the file is not downloaded:
.\Test>ufs put test.log
.\Test>ufs get test.log
 ║ ═
              ?       ! " # $ % & ' ( ) * + , - . / 0 1 ╝
.\Test>

Thank you

**Comment by dpgeorge** [comment]
Thanks @alexandros769 for the test, I can reproduce the problem.

The issue is that `test.log` has control characters in it (ctrl-C and ctrl-D) which interfere with the file download process.  So these would need to be escaped by the download code for it to work.  Here is a quick patch I made that seems to fix the issue:
```diff
--- a/microfs.py
+++ b/microfs.py
@@ -273,13 +273,16 @@ def get(filename, target=None, serial=None):
         "f = open('{}', 'rb')".format(filename),
         "r = f.read",
         "result = True",
-        "while result:\n result = r(32)\n if result:\n  u.write(result)\n",
+        "while result:\n result = r(32)\n if result:\n  u.write(repr(result))\n",
         "f.close()",
     ]
     out, err = execute(commands, serial)
     if err:
         raise IOError(clean_error(err))
     # Recombine the bytes while removing "b'" from start and "'" from end.
+    assert out.startswith(b"b'")
+    assert out.endswith(b"'")
+    out = eval(b"".join(out.split(b"'b'")))
     with open(target, 'wb') as f:
         f.write(out)
     return True
```
@ntoll sorry it's not a proper PR!

**Comment by dpgeorge** [comment]
An alternative solution to the above would be to write the length of `result` before writing it, and then in the reading code on the PC side read this length first then read that many bytes.  The issue is that it currently reads until ctrl-D which appears in the stream of data in the file, so reading ends prematurely.

**Comment by alexandros769** [comment]
Thanks,
I tried this modification you posted and it works for me. I have also checked that the content of the file I uploaded is binary same to the one I downloaded.

**Comment by ntoll** [comment]
Hi folks... just pushed this fix with updates to the test suite. Thanks for the contributions..!

I've also updated the package on PyPi and ReadTheDocs (https://microfs.readthedocs.io/en/latest/#id1).

:+1:

**Comment by alexandros769** [comment]
> Hi folks... just pushed this fix with updates to the test suite. Thanks for the contributions..!
> 
> I've also updated the package on PyPi and ReadTheDocs (https://microfs.readthedocs.io/en/latest/#id1).
> 
> 👍

Thanks, could it be that you forgot the commas in join command? I get a syntax error and if I add the commas it works.

**Comment by ntoll** [comment]
@alexandros769 you're going to have to let me know exactly what you're on about here, otherwise I'm guessing. Please paste in the error message you see and describe *precisely* what it is you did to rectify it.

**Comment by alexandros769** [comment]
It's the same test I described before:
(venv) C:\Repos\fdtt_investigation\Test>ufs put test.file

(venv) C:\Repos\fdtt_investigation\Test>ufs get test.file
SyntaxError: invalid syntax

**Comment by ntoll** [comment]
@alexandros769 aha... I see what you mean. Just pushed a fix and updated on PyPI. :+1:
