### ISSUE TITLE
Hex files on the latest BBC micro:bit revision

### ISSUE THREAD

**Issue by oivron** [ntoll/microfs#24]
Do you plan to support the new micro:bit v2? Or does microfs support it already? I'm a bit concerned about this information: [https://tech.microbit.org/software/hex-format/#universal-hex-files](https://tech.microbit.org/software/hex-format/#universal-hex-files).

Unfortunately, I do not have the new micro:bit yet.

**Comment by ntoll** [comment]
Yes, we're waiting on the micro:bit foundation to release the hex file for MicroPython (that is compatible with both v1 and v2).
