### ISSUE TITLE
Support for micro:bit V2

### ISSUE THREAD

**Issue by oivron** [ntoll/microfs#26]
Any news on V2 support yet?

**Comment by ntoll** [comment]
@carlosperate ?

**Comment by carlosperate** [comment]
Should be fully supported, this is what Mu uses to transfer files via serial to micro:bit V2 and other MicroPython boards.

**Comment by oivron** [comment]
You are right! I did some testing earlier (after new uflash) and it didn't work on V2 with additional third-party modules. Probably my mistake. I use a module bitbot.py (for the 4tronix Bit:bot XL robot).

myscript.py:

```
from microbit import *
from bitbot import *

bitbot.go(FORWARD, 40)
```

Here's what I do:

`uflash .\myscript.py`

After this there is an error on the micro:bit: "Import error No module named bitbot". Which is ok.

And then:

`ufs put C:\Users\..\bitbot.py`

After this the robot does what it should.

Is this the correct way to use uflash and microfs?

**Comment by carlosperate** [comment]
Yeah, that will work!
I personally first just flash the micro:bit with MicroPython (you can do that with uFlash by not specifying a script) and then just send the modules first and then the main.py script.

**Comment by oivron** [comment]
Like this?

```
> uflash
> ufs put C:\Users\..\bitbot.py
> uflash .\myscript.py
```

In that case I end up with:  "Import error No module named bitbot".

**Comment by carlosperate** [comment]
if you rename `myscript.py` to `main.py` it would be like this:

```
uflash
ufs put C:\Users\..\bitbot.py
ufs put .\main.py
```

**Comment by oivron** [comment]
Wonderful! Thank you!

**Comment by oivron** [comment]
Actually, running the three commands above from my VSCode extension or from a Powershell file does not work with V2, only with V1.

V2:
```
PS C:\Users\Test\Documents\Code> uflash.exe
Flashing Python to: D:\micropython.hex
PS C:\Users\Test\Documents\Code> ufs put C:\users\test\python\lib\site-packages\bitbot.py
b'MicroPython v1.13 on 2021-03-16; micro:bit v2.0.0-beta.5 with nRF52833\r\nType "help()" for more information.\r\n>>> '
Could not enter raw REPL.
PS C:\Users\Test\Documents\Code> ufs put C:\users\test\documents\Code\my.py main.py      
PS C:\Users\Test\Documents\Code>
```

The microbit shows "Line 2 import error no module named 'bitbot'". However, running each of the commands manually works fine.

- Windows 10
- Python 3.9.6
- microfs 1.4.3
- uflash 2.0.0
- microbit V2 Interface version : 0255

**Comment by carlosperate** [comment]
@ntoll this can be closed.
