### ISSUE TITLE
Can't retrieve my program using ufs get

### ISSUE THREAD

**Issue by rhubarbdog** [ntoll/microfs#35]
i flashed the microbit (v1) with the `uflash` command then copied my program using `ufs put program.py main.py`
i tried to retrieve the program back to my laptop with `ufs get main.py` nothing was transferred from the microbit, but when i `ufs ls` the file `main.py` exists on the microbit

**Comment by carlosperate** [comment]
Does microFS throw any exception?

**Comment by rhubarbdog** [comment]
i don't believe it did, but i no longer have any of the programs avaialble it's a new laptop. lost all my backups and laptop. i often do get OS errors with `ufs` but i just try the command again.
